### ISSUE TITLE
bug: input not editable when linkState used with default value

### ISSUE THREAD

**Issue by CezaryDanielNowak** [srph/react-link-state#5]
In following situation everything works smooth:

```
export default class SomeComponent extends React.Component {
  state = {
    phoneNumber: null
  }
  render() {
    return <input tyle="text" valueLink={linkState(this, 'phoneNumber')} />
  }
}
```

But in case when I have default value, input is not editable anymore:

```
export default class SomeComponent extends React.Component {
  state = {
    phoneNumber: '+48'
  }
  render() {
    return <input tyle="text" valueLink={linkState(this, 'phoneNumber')} />
  }
}
```

**Comment by srph** [comment]
That's weird, but thanks for bringing this up! It seems to be working fine right now. Can you put up some working example? I don't think I made some UMD releases, so I'll need a repo. Sorry about that.

What React version are you using?

---

I have a deadline in around 3 hours, so I'll probably be able to do some tests after the day.

**Comment by CezaryDanielNowak** [comment]
Wow, you rock!
React 0.14.7, React-DOM 0.14.7, react-link state 0.1.1 and master

**Comment by srph** [comment]
Hm.. it's working.

https://github.com/chirigarikku/react-link-state-issue5

**Comment by CezaryDanielNowak** [comment]
Thank you for test build.
Looks like problem is caused by pure render mixin:

https://github.com/CezaryDanielNowak/react-link-state-issue5/commit/aaa1d4a3206c2a16d016da96c57e07155d6510d6

**Comment by CezaryDanielNowak** [comment]
And looks like, it can't be fixed easly:
https://github.com/gaearon/react-pure-render#known-issues

> If a component in the middle of your rendering chain has pure rendering, but some nested component relies on a context change up the tree, the nested component won't learn about context change and won't update. This is a known React issue that exists because context is not a documented feature and is not finished

**Comment by srph** [comment]
Ay, sadly :(. I think that resolves it. Closing this.
